name: üçø On Release Published
run-name: Release ${{github.ref_name}}

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 9.0.100

      - name: Download Release artifacts
        uses: robinraju/release-downloader@v1.11
        with:
          tag: ${{github.ref_name}}
          fileName: '*.nupkg'

      - name: Publish NuGet
        run: dotnet nuget push *.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
